-- ====================================================================
-- SEED DATA: COMPLETE EXERCISE LIBRARY & EXPANDED LEARNING HUB
-- ====================================================================
USE `fitness_tracker_db`;

TRUNCATE TABLE `exercises`;

INSERT INTO `exercises` (
    `id`, `name`, `slug`, `category`, `difficulty`, `equipment`, 
    `target_muscles`, `secondary_muscles`, `description`, `instructions`, 
    `common_mistakes`, `form_tips`, `safety_tips`, `default_sets`, 
    `default_reps`, `default_duration_seconds`, `rest_time_seconds`, 
    `video_url`, `thumbnail_url`, `status`
) VALUES
-- ==================== CORE ====================
(1, 'Light Plank', 'light-plank', 'Core', 'Beginner', 'No Equipment / Mat',
 'Transverse Abdominis, Rectus Abdominis', 'Glutes, Obliques, Shoulders',
 'A foundational isometric core stabilization exercise that trains anti-extension and pelvic control.',
 'Step 1\nGet into a prone position on a comfortable mat resting on your forearms.\n\nStep 2\nPosition your elbows directly underneath your shoulders with forearms parallel to each other.\n\nStep 3\nExtend legs behind you on your toes, setting feet hip-width apart.\n\nStep 4\nBrace your abdominal wall firmly and gently tuck your pelvis into a posterior pelvic tilt.\n\nStep 5\nKeep your neck neutral by gazing at the floor slightly ahead of your hands.\n\nStep 6\nHold the rigid straight line position while breathing smoothly through your diaphragm.',
 'Hips sagging toward the floor, hiking hips too high in a tent shape, holding breath, letting shoulder blades wing out.',
 'Actively pull your elbows downward toward your toes to generate full-body abdominal tension (irradiation).',
 'Stop immediately if you feel compressive discomfort in your lower lumbar spine.',
 3, '20-30 seconds', 30, 45, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 'assets/images/content/cardio.webp', 'ACTIVE'),

(2, 'Side Plank', 'side-plank', 'Core', 'Beginner', 'No Equipment / Mat',
 'Internal & External Obliques', 'Quadratus Lumborum, Gluteus Medius, Deltoids',
 'Unilateral lateral core exercise that fortifies the obliques and shields the lower back against rotational shear.',
 'Step 1\nLie on your side with legs extended straight and feet stacked directly on top of each other.\n\nStep 2\nPlace your bottom elbow directly below your shoulder with forearm flat on the floor.\n\nStep 3\nLift hips off the floor until your body forms a straight diagonal line from head to ankles.\n\nStep 4\nPlace top hand on your hip or extend it vertically toward the ceiling.\n\nStep 5\nHold the position with a firm glute contraction and steady rhythmic breathing.\n\nStep 6\nSlowly lower hips back to the floor and switch to the opposite side.',
 'Sagging hips downward, rolling top shoulder forward, bending knees or arching spine.',
 'Think of pushing the bottom hip up toward the ceiling while maintaining strong thoracic posture.',
 'If stacked feet cause ankle discomfort, stagger your feet with the top foot forward.',
 3, '20-30 seconds/side', 30, 45, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', 'assets/images/content/cardio.webp', 'ACTIVE'),

(3, 'Plank Shoulder Tap', 'plank-shoulder-tap', 'Core', 'Intermediate', 'No Equipment',
 'Transverse Abdominis, Obliques', 'Anterior Deltoids, Serratus Anterior, Glutes',
 'Dynamic anti-rotational core movement that challenges shoulder stability while preventing torso twist.',
 'Step 1\nAssume a high plank push-up position with hands directly under shoulders and feet slightly wider than hip-width.\n\nStep 2\nBrace your core and glutes to lock your pelvis completely stationary.\n\nStep 3\nSlowly lift right hand and tap your left shoulder in a controlled tempo.\n\nStep 4\nReturn right hand to the ground without shifting weight abruptly.\n\nStep 5\nLift left hand and tap your right shoulder.\n\nStep 6\nAlternate sides in a rhythmic, measured cadence.',
 'Rocking hips side-to-side, letting hands drift ahead of shoulders, rushing the tapping motion.',
 'Imagine balancing a full glass of water on your lower back; zero hip wobble is the goal.',
 'Widen your foot stance if you find your hips swaying excessively.',
 3, '12-16 taps', 40, 45, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', 'assets/images/content/cardio.webp', 'ACTIVE'),

(4, 'Mountain Climbers', 'mountain-climbers', 'Core', 'Beginner', 'No Equipment',
 'Rectus Abdominis, Hip Flexors', 'Shoulders, Quadriceps, Cardiovascular System',
 'High-energy dynamic core builder combining horizontal running mechanics with isometric upper body stability.',
 'Step 1\nStart in a high plank position with wrists beneath shoulders and spine neutral.\n\nStep 2\nEngage core and drive right knee smoothly toward your chest.\n\nStep 3\nReturn right leg to starting position while simultaneously driving left knee forward.\n\nStep 4\nMaintain a swift, continuous piston-like leg alternating cadence.\n\nStep 5\nKeep hips level with shoulders and avoid excessive vertical bounce.\n\nStep 6\nContinue for the target duration while focusing on rhythmic breathing.',
 'Bouncing hips up into the air, rounded lower back, landing flat-footed instead of on toe balls.',
 'Keep your shoulder blades pulled down away from your ears to maintain rigid pushing power.',
 'Perform at a controlled slow tempo first before accelerating into high-speed intervals.',
 3, '30-45 seconds', 45, 45, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4', 'assets/images/content/cardio.webp', 'ACTIVE'),

(5, 'Dead Bug', 'dead-bug', 'Core', 'Beginner', 'No Equipment / Mat',
 'Transverse Abdominis, Deep Core', 'Hip Flexors, Anterior Deltoids, Pelvic Floor',
 'Premier clinical core stabilization exercise that teaches anterior pelvic control and contralateral coordination.',
 'Step 1\nLie flat on your back on a mat with arms extended straight toward the ceiling over your chest.\n\nStep 2\nBend knees at a 90-degree angle with knees stacked directly over hips (tabletop position).\n\nStep 3\nPress your lumbar spine flat against the floor, eliminating any lower back gap.\n\nStep 4\nInhale and slowly lower right arm overhead while extending left leg forward just above the floor.\n\nStep 5\nExhale and return both limbs to starting position, keeping back glued to the floor.\n\nStep 6\nRepeat with left arm and right leg.',
 'Allowing lower back to arch off the floor, moving non-working limbs, rushing through the extension.',
 'Keep your abdominal brace constant; the moment your lower back leaves the floor, shorten your leg range.',
 'Do not extend your heel all the way to the floor if you lose pelvic control.',
 3, '10-12 reps/side', 45, 45, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', 'assets/images/content/cardio.webp', 'ACTIVE'),

(6, 'Bird Dog', 'bird-dog', 'Core', 'Beginner', 'No Equipment / Mat',
 'Erector Spinae, Gluteus Maximus', 'Core, Deltoids, Hamstrings',
 'Posterior chain and core coordination staple that restores spinal stabilization without spinal loading.',
 'Step 1\nStart on all fours in quadruped position with hands under shoulders and knees under hips.\n\nStep 2\nEnsure your neck is in line with your spine, looking down at the mat.\n\nStep 3\nBrace your abs and simultaneously extend right arm forward and left leg straight back.\n\nStep 4\nReach heel toward the back wall until leg and arm are parallel with the floor.\n\nStep 5\nHold for 2 seconds at the peak while squeezing your glute.\n\nStep 6\nSlowly return to all fours and alternate to left arm and right leg.',
 'Hyperextending the lower back, lifting leg too high above hip level, rotating pelvis sideways.',
 'Focus on reaching your fingers and toes as far apart as possible rather than kicking upward.',
 'Keep your hips squared to the floor throughout the entire reach.',
 3, '10-12 reps/side', 40, 45, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4', 'assets/images/content/mobility.webp', 'ACTIVE'),

-- ==================== CHEST ====================
(7, 'Push-Up', 'push-up', 'Chest', 'Beginner', 'No Equipment',
 'Pectoralis Major, Sternal Head', 'Triceps Brachii, Anterior Deltoid, Core',
 'The gold standard upper-body pushing exercise for chest thickness, tricep power, and core endurance.',
 'Step 1\nPlace hands on floor slightly wider than shoulder width with fingers pointing forward.\n\nStep 2\nStep feet back into a strong high plank, squeezing glutes and engaging your core.\n\nStep 3\nInhale and lower your chest by bending elbows at roughly a 45-degree angle from your ribs.\n\nStep 4\nDescend until your chest is approximately 2 inches off the ground.\n\nStep 5\nExhale and drive powerfully through your palms to return to top plank.\n\nStep 6\nLock out elbows smoothly without hyperextending.',
 'Flaring elbows outward at 90 degrees (impinges shoulders), sagging lumbar spine, incomplete depth.',
 'Screw your palms into the floor to generate external shoulder rotation torque and joint stability.',
 'Elevate hands on a bench or sturdy surface if floor push-ups cause wrist pain.',
 3, '12-15 reps', 45, 60, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

(8, 'Incline Push-Up', 'incline-push-up', 'Chest', 'Beginner', 'Bench / Platform',
 'Lower Pectoralis, Triceps', 'Anterior Deltoids, Core',
 'Regressed pushing variation that reduces gravitational load, ideal for beginners building volume.',
 'Step 1\nPlace hands on an elevated bench or sturdy platform, shoulder-width apart.\n\nStep 2\nWalk feet back until your body forms a straight diagonal plank.\n\nStep 3\nLower your chest smoothly toward the edge of the bench with elbows at 45 degrees.\n\nStep 4\nLightly touch the platform with your lower chest.\n\nStep 5\nPush forcefully back to the top lockout position.\n\nStep 6\nKeep your core braced so your hips move in perfect unison with your chest.',
 'Bending at the hips, setting bench too low too soon, loose neck posture.',
 'The higher the platform, the easier the push-up; gradually decrease platform height as strength grows.',
 'Ensure the bench or platform is completely stable and will not slide during the set.',
 3, '12-15 reps', 40, 45, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

(9, 'Dumbbell Bench Press', 'dumbbell-bench-press', 'Chest', 'Intermediate', 'Dumbbells, Flat Bench',
 'Pectoralis Major (Mid & Lower fibers)', 'Anterior Deltoids, Triceps Brachii',
 'Premier free-weight compound exercise allowing deep natural range of motion and bilateral chest symmetry.',
 'Step 1\nSit on edge of flat bench with dumbbells resting vertically on your thighs.\n\nStep 2\nLie back smoothly while kicking weights up to chest level.\n\nStep 3\nRetract your scapulae (pull shoulder blades together and down into the pad).\n\nStep 4\nPress dumbbells upward in a slight arc until arms are extended over chest without touching bells.\n\nStep 5\nLower dumbbells under 3-second control until you feel a comfortable deep chest stretch.\n\nStep 6\nDrive upward through your chest to complete the rep.',
 'Flaring elbows excessively, letting weights clank together at peak, arching lower back off pad.',
 'Keep your feet planted flat on the floor to drive leg tension up into the press.',
 'Always use safety spotters or lower dumbbells safely to knees when training near failure.',
 4, '8-10 reps', 45, 90, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

(10, 'Chest Fly', 'chest-fly', 'Chest', 'Intermediate', 'Dumbbells / Bench',
 'Sternal Pectoralis, Clavicular Head', 'Anterior Deltoids, Biceps (isometric)',
 'Isolation movement providing intense chest stretch under mechanical tension without heavy tricep involvement.',
 'Step 1\nLie on flat bench with dumbbells extended directly over chest with a neutral grip (palms facing).\n\nStep 2\nMaintain a slight 10-15 degree bend in your elbows throughout the movement.\n\nStep 3\nInhale and open arms out wide in a sweeping arc until dumbbells are level with chest.\n\nStep 4\nFeel a deep horizontal abduction stretch across your pecs.\n\nStep 5\nExhale and hug your arms back together, squeezing the chest at the top contraction.\n\nStep 6\nKeep elbows fixed in the same slight bend without pressing.',
 'Turning the fly into a press by bending elbows too much, overstretching shoulders past comfort zone.',
 'Imagine hugging a wide tree trunk: lead with your chest and maintain a fixed elbow angle.',
 'Use moderate weights to protect the anterior shoulder capsule from hyperextension.',
 3, '12-15 reps', 45, 60, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

-- ==================== BACK ====================
(11, 'Lat Pulldown', 'lat-pulldown', 'Back', 'Beginner', 'Cable Pulldown Machine',
 'Latissimus Dorsi', 'Biceps Brachii, Rhomboids, Rear Delts, Forearms',
 'Foundational vertical pulling machine movement for building upper back width and V-taper aesthetics.',
 'Step 1\nSit at lat pulldown station with thighs secured firmly under the roller pads.\n\nStep 2\nGrip the wide bar with an overhand grip slightly outside shoulder width.\n\nStep 3\nSit upright with a slight 10-degree lean back and proud chest.\n\nStep 4\nPull the bar down toward your upper chest, driving elbows downward and back.\n\nStep 5\nSqueeze lats hard at bottom for 1 second, keeping collarbones wide.\n\nStep 6\nSlowly control the bar back up to full overhead stretch with locked scapular control.',
 'Yanking the bar down with momentum, leaning back too far (turns into a row), pulling behind the neck.',
 'Think of driving your elbows into your back pockets rather than pulling with your hands.',
 'Keep wrists straight and avoid pulling the bar behind your neck.',
 3, '10-12 reps', 45, 60, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

(12, 'Dumbbell Row', 'dumbbell-row', 'Back', 'Beginner', 'Dumbbell, Flat Bench',
 'Latissimus Dorsi, Rhomboids', 'Biceps, Rear Deltoids, Trapezius',
 'Unilateral horizontal rowing builder that eliminates back asymmetry and strengthens spinal anti-rotation.',
 'Step 1\nPlace left knee and left hand flat on bench with spine parallel to floor.\n\nStep 2\nHold a dumbbell in your right hand with arm hanging straight down.\n\nStep 3\nKeep your core braced and gaze slightly forward to maintain a neutral cervical spine.\n\nStep 4\nPull dumbbell upward in a slight arc toward your hip crease, driving with elbow.\n\nStep 5\nRetract your shoulder blade tightly at peak contraction for 1 second.\n\nStep 6\nLower the dumbbell smoothly back down to full arm hang.',
 'Rotating torso to hoist weight, pulling vertically to armpit rather than sweeping to hip.',
 'Pull through the elbow, not the hand; imagine your forearm is merely a cable hook.',
 'Keep your lower back flat; never allow lumbar rounding during heavy pulls.',
 3, '10-12 reps/side', 45, 60, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

(13, 'Seated Cable Row', 'seated-cable-row', 'Back', 'Intermediate', 'Seated Cable Row Machine',
 'Mid-Trapezius, Rhomboids, Lats', 'Biceps Brachii, Rear Delts, Erector Spinae',
 'Horizontal cable rowing staple for building dense mid-back thickness and postural integrity.',
 'Step 1\nSit on the rowing bench with feet on footrests and knees slightly bent.\n\nStep 2\nGrip the V-handle attachment with arms extended and sit tall with neutral spine.\n\nStep 3\nInitiate the pull by retracting scapulae, then pull handle into lower abdomen.\n\nStep 4\nDrive elbows back behind your torso while keeping chest high.\n\nStep 5\nPause and contract mid-back muscles hard for 1 second.\n\nStep 6\nExtend arms smoothly back forward, allowing shoulder blades to protract slightly.',
 'Rocking torso back and forth excessively, shrugging shoulders up toward ears, rounding lower back.',
 'Keep a fixed tall posture throughout; do not use lumbar momentum to jerk the weight.',
 'Do not lock your knees out completely; keep a soft bend to protect hamstrings.',
 3, '10-12 reps', 45, 60, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

(14, 'Face Pull', 'face-pull', 'Back', 'Beginner', 'Cable Machine, Rope Attachment',
 'Rear Deltoids, Infraspinatus, Rhomboids', 'Trapezius, External Rotators',
 'The ultimate postural and rotator cuff health exercise for countering desk posture and rounded shoulders.',
 'Step 1\nSet cable pulley to eye height with rope attachment.\n\nStep 2\nStep back with a staggered stance, gripping rope with thumbs facing backward.\n\nStep 3\nPull the center of the rope directly toward your bridge of nose / eyes.\n\nStep 4\nAs the rope nears your face, externally rotate shoulders, pulling rope ends apart.\n\nStep 5\nSqueeze upper back and rear delts in double-bicep pose position.\n\nStep 6\nControl weight smoothly back to starting position.',
 'Using too much weight, pulling down to chest, leaning backward to compensate.',
 'Think of showing your knuckles behind you at the end of the pull for peak external rotation.',
 'Use light-to-moderate weights with high control and strict execution.',
 3, '15-20 reps', 45, 45, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

-- ==================== SHOULDERS ====================
(15, 'Shoulder Press', 'shoulder-press', 'Shoulders', 'Intermediate', 'Dumbbells',
 'Anterior & Lateral Deltoids', 'Triceps, Upper Chest, Trapezius, Core',
 'Primary vertical pressing movement for developing broad 3D shoulder caps and overhead pressing power.',
 'Step 1\nSit on an upright bench or stand with feet shoulder-width apart.\n\nStep 2\nHold dumbbells at shoulder level with knuckles facing ceiling and palms forward.\n\nStep 3\nBrace core and squeeze glutes to establish a solid foundation.\n\nStep 4\nPress dumbbells upward in a smooth arc overhead until arms are extended.\n\nStep 5\nPause at the top without clanking dumbbells together.\n\nStep 6\nLower dumbbells under control over 2-3 seconds back to ear level.',
 'Overarching the lower back, pressing weights too far forward, dropping weights abruptly.',
 'Keep ribs locked down toward pelvis to avoid hyperextending your lumbar spine.',
 'Lower weights under full muscular control; do not bounce at bottom.',
 3, '8-12 reps', 45, 75, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

(16, 'Lateral Raise', 'lateral-raise', 'Shoulders', 'Beginner', 'Light Dumbbells',
 'Lateral Deltoids (Side Cap)', 'Upper Trapezius, Forearms',
 'Essential isolation exercise for building deltoid width and the coveted athletic V-taper physique.',
 'Step 1\nStand tall with light dumbbells at sides and palms facing thighs.\n\nStep 2\nHinge slightly forward 5 degrees at hips with a soft bend in elbows.\n\nStep 3\nRaise arms outward in the scapular plane (30 degrees forward of direct lateral).\n\nStep 4\nLift until elbows reach shoulder height, leading with elbows rather than wrists.\n\nStep 5\nHold for a split-second at peak contraction.\n\nStep 6\nLower dumbbells smoothly over 3 seconds back to sides.',
 'Using momentum/swinging, raising hands higher than elbows, shrugging traps excessively.',
 'Pour the water: imagine slightly angling your thumbs down at top to keep focus on side delts.',
 'Use lighter weights with strict form; heavy swinging only taxes traps and joints.',
 4, '12-15 reps', 40, 45, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

(17, 'Front Raise', 'front-raise', 'Shoulders', 'Beginner', 'Dumbbells / Plate',
 'Anterior Deltoids (Front Shoulder)', 'Upper Pectoralis, Serratus Anterior',
 'Targeted isolation builder for anterior shoulder head development and forward flexion stability.',
 'Step 1\nStand upright holding dumbbells resting against front of thighs.\n\nStep 2\nMaintain a tall chest, tight core, and soft bend in elbows.\n\nStep 3\nRaise one or both dumbbells straight forward in front of you.\n\nStep 4\nLift until weights reach eye/shoulder level with knuckles facing up.\n\nStep 5\nPause at the apex for peak tension.\n\nStep 6\nLower the weights smoothly under strict eccentric control.',
 'Rocking body backward to hoist weight, raising arms way above eye level, bending elbows too much.',
 'Keep torso completely stationary and resist the urge to bounce off thighs.',
 'Do not raise weights above eye line to avoid subacromial impingement.',
 3, '12-15 reps', 40, 45, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

(18, 'Rear Delt Fly', 'rear-delt-fly', 'Shoulders', 'Beginner', 'Light Dumbbells',
 'Posterior Deltoids (Rear Shoulder)', 'Rhomboids, Mid-Trapezius, Infraspinatus',
 'Crucial shoulder isolation movement for fixing round-shoulder imbalances and rounding out 3D delts.',
 'Step 1\nStand with feet hip-width and hinge forward at hips until torso is nearly parallel to floor.\n\nStep 2\nHold light dumbbells hanging straight down with palms facing inward.\n\nStep 3\nKeep a slight bend in elbows and maintain flat spine posture.\n\nStep 4\nRaise arms out to sides in a wide sweeping arc, leading with elbows.\n\nStep 5\nSqueeze rear shoulders hard at top without shrugging neck.\n\nStep 6\nLower dumbbells smoothly back to center.',
 'Standing too upright, pulling with triceps/biceps, jerking torso upward.',
 'Keep your head in neutral alignment and gaze at floor about 3 feet ahead.',
 'Focus on pulling your elbows wide apart rather than pulling shoulder blades together.',
 3, '15-20 reps', 40, 45, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

-- ==================== ARMS ====================
(19, 'Bicep Curl', 'bicep-curl', 'Arms', 'Beginner', 'Dumbbells',
 'Biceps Brachii (Short & Long heads)', 'Brachialis, Brachioradialis',
 'The classic arm builder for peaked bicep hypertrophy and elbow flexion power.',
 'Step 1\nStand tall holding dumbbells at sides with palms facing thighs (neutral grip).\n\nStep 2\nPin upper arms tight to your torso; keep elbows stationary beside ribs.\n\nStep 3\nCurl dumbbells upward while supinating wrists so palms face up by mid-rep.\n\nStep 4\nContract biceps forcefully at the top of the curl near shoulder height.\n\nStep 5\nPause for 1 second at peak contraction.\n\nStep 6\nLower dumbbells under 3-second control back to full extension at thighs.',
 'Swinging hips to cheat weights up, allowing elbows to drift forward, cutting bottom range of motion.',
 'Supinate fully at the top: rotate pinky finger slightly higher than thumb for peak bicep recruitment.',
 'Avoid hyperextending elbows at the bottom; maintain active muscle tension.',
 3, '10-12 reps', 45, 60, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

(20, 'Hammer Curl', 'hammer-curl', 'Arms', 'Beginner', 'Dumbbells',
 'Brachialis, Brachioradialis', 'Biceps Brachii, Forearm Flexors',
 'Neutral-grip arm staple that pushes the bicep peak upward and builds thick, dense forearms.',
 'Step 1\nStand tall with dumbbells hanging at sides, palms facing inward toward each other.\n\nStep 2\nKeep wrists neutral throughout the entire repetition (no wrist rotation).\n\nStep 3\nPin elbows against ribs and curl dumbbells upward in a hammer-striking motion.\n\nStep 4\nLift until dumbbells are near chest level with thumbs pointing toward shoulders.\n\nStep 5\nSqueeze forearms and brachialis hard at peak.\n\nStep 6\nLower slowly through a full controlled stretch.',
 'Swinging upper body, allowing elbows to flare outward, using wrist flicking at top.',
 'Keep your grip firm and imagine hammering a nail directly in front of you.',
 'Perform alternating or simultaneous curls depending on stability preference.',
 3, '10-12 reps', 45, 60, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

(21, 'Tricep Extension', 'tricep-extension', 'Arms', 'Intermediate', 'Dumbbell / Bench',
 'Triceps Brachii (Long Head)', 'Anconeus, Core Stability',
 'Overhead triceps movement that places the long head under maximum passive stretch for superior growth.',
 'Step 1\nSit on bench with back support. Grip a single dumbbell vertically with both hands under top plate.\n\nStep 2\nPress dumbbell directly overhead to full arm extension.\n\nStep 3\nKeep upper arms tucked close to head with elbows pointing forward.\n\nStep 4\nLower dumbbell behind head by flexing elbows until forearms pass 90 degrees.\n\nStep 5\nFeel deep stretch across the back of upper arms.\n\nStep 6\nExtend elbows forcefully to return dumbbell to overhead lockout.',
 'Flaring elbows wide to sides, arching lower back excessively, dropping weight too fast.',
 'Keep elbows pinned forward and core braced tight against the back pad.',
 'Ensure a secure two-handed diamond grip under the dumbbell bell before lifting.',
 3, '10-12 reps', 45, 60, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

(22, 'Tricep Pushdown', 'tricep-pushdown', 'Arms', 'Beginner', 'Cable Machine, Straight or V-Bar',
 'Triceps Brachii (Lateral & Medial heads)', 'Forearms, Anconeus',
 'High-efficiency cable isolation exercise delivering constant tension on triceps through lockout.',
 'Step 1\nAttach straight bar or V-bar to high cable pulley. Stand with slight forward hip hinge.\n\nStep 2\nGrip bar with overhand grip and pin upper arms tight against ribs.\n\nStep 3\nStart with forearms at slightly above 90 degrees.\n\nStep 4\nPush bar down smoothly until arms are fully locked out at thighs.\n\nStep 5\nSqueeze triceps forcefully at the bottom for 1 second.\n\nStep 6\nAllow bar to rise under control back to 90 degrees without moving elbows.',
 'Letting elbows travel forward and back, leaning body over bar to use bodyweight, wrist bending.',
 'Keep your upper arms locked like statues; all movement occurs solely at the elbow hinge.',
 'Maintain a neutral wrist position to prevent wrist strain under heavier loads.',
 3, '12-15 reps', 45, 45, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

-- ==================== LEGS ====================
(23, 'Bodyweight Squat', 'bodyweight-squat', 'Legs', 'Beginner', 'No Equipment',
 'Quadriceps, Gluteus Maximus', 'Hamstrings, Adductors, Core, Calves',
 'Fundamental lower-body human movement pattern that builds leg power, hip mobility, and knee stability.',
 'Step 1\nStand with feet shoulder-width apart, toes turned outward 15-20 degrees.\n\nStep 2\nKeep chest proud, gaze forward, and arms extended forward for balance.\n\nStep 3\nInhale, brace core, and initiate squat by breaking at hips and knees simultaneously.\n\nStep 4\nDescend until thighs are parallel to floor or hip crease is below knee caps.\n\nStep 5\nKeep knees tracking in line with toes and heels flat on ground.\n\nStep 6\nExhale and drive through mid-foot to stand back tall, locking glutes at top.',
 'Knees caving inward (valgus collapse), heels lifting off floor, rounding lower back at bottom.',
 'Push the floor away with your whole foot and actively push knees outward on descent.',
 'Maintain upright posture; do not collapse torso onto thighs.',
 3, '15-20 reps', 45, 60, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

(24, 'Lunges', 'lunges', 'Legs', 'Beginner', 'No Equipment / Dumbbells',
 'Quadriceps, Glutes', 'Hamstrings, Calves, Core Balance',
 'Unilateral lower body staple that improves balance, pelvic stability, and functional athletic agility.',
 'Step 1\nStand tall with feet hip-width apart and hands on hips or at sides.\n\nStep 2\nTake a controlled large step forward with your right leg.\n\nStep 3\nLower hips until both front and back knees are bent at roughly 90-degree angles.\n\nStep 4\nKeep front knee stacked over ankle and rear knee hovering 1 inch above floor.\n\nStep 5\nDrive forcefully through front heel to push back to standing.\n\nStep 6\nRepeat on left leg in alternating fashion.',
 'Leaning torso forward over front knee, slamming rear knee into floor, narrow tightrope footing.',
 'Keep your feet on railroad tracks (hip-width) rather than a balance beam for better stability.',
 'Do not allow the front knee to collapse inward or shoot past toes.',
 3, '10-12 reps/leg', 45, 60, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

(25, 'Bulgarian Split Squat', 'bulgarian-split-squat', 'Legs', 'Intermediate', 'Bench / Platform',
 'Quadriceps, Gluteus Maximus', 'Hamstrings, Calves, Core Stability',
 'High-intensity unilateral movement that destroys leg imbalances and builds massive glute/quad power.',
 'Step 1\nStand 2-3 feet in front of a flat bench. Place top of rear foot flat on bench surface.\n\nStep 2\nKeep torso upright or slight 10-degree forward hinge to target glutes.\n\nStep 3\nLower hips straight down like an elevator until front thigh is parallel to floor.\n\nStep 4\nBack knee should descend close to the floor without touching.\n\nStep 5\nDrive through front heel and mid-foot to rise back to starting position.\n\nStep 6\nComplete all reps on one leg before switching sides.',
 'Placing front foot too close to bench (knee jamming), shifting weight to back foot, torso tilting sideways.',
 'Keep 85% of your bodyweight firmly centered over your front foot throughout.',
 'Use bodyweight first before adding dumbbells to master balance and alignment.',
 3, '8-10 reps/leg', 45, 60, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

(26, 'Calf Raise', 'calf-raise', 'Legs', 'Beginner', 'Step / Platform',
 'Gastrocnemius, Soleus', 'Tibialis Posterior, Foot Intrinsic Muscles',
 'Targeted lower leg builder for ankle stability, vertical jump power, and athletic sprint mechanics.',
 'Step 1\nStand with balls of feet on edge of a step or platform, heels hanging off.\n\nStep 2\nLightly hold a rail or wall for balance.\n\nStep 3\nLower heels below step level into a deep, comfortable calf stretch for 1 second.\n\nStep 4\nDrive up forcefully onto balls of feet as high as possible.\n\nStep 5\nSqueeze calves tightly at peak plantarflexion for 1 full second.\n\nStep 6\nLower slowly over 3 seconds back into the deep stretch.',
 'Bouncing at bottom using Achilles tendon elasticity, bending knees to cheat, incomplete height.',
 'Pause 1 second at the bottom stretch and 1 second at the top contraction to remove tendon recoil.',
 'Perform smoothly without sudden jerking to protect the Achilles tendon.',
 3, '15-20 reps', 45, 45, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

(27, 'Leg Press', 'leg-press', 'Legs', 'Intermediate', 'Leg Press Machine',
 'Quadriceps, Glutes', 'Hamstrings, Calves',
 'Heavy compound lower body machine exercise that overloads leg musculature without spinal compression.',
 'Step 1\nSit in leg press machine with back and head resting comfortably against padded support.\n\nStep 2\nPlace feet on sled platform shoulder-width apart in middle of plate.\n\nStep 3\nDisengage safety locks and grasp side support handles.\n\nStep 4\nInhale and lower the sled smoothly until knees form a 90-degree angle.\n\nStep 5\nEnsure lower back remains firmly glued to the back pad (no pelvis tucking).\n\nStep 6\nExhale and drive through feet to press sled back up without hyperextending knees.',
 'Allowing pelvis to curl off the seat at bottom (lumbar shear), locking knees rigidly at top.',
 'Never fully snap or hyperextend your knees at the top; maintain soft knee tension.',
 'Always set the mechanical safety stops at a depth that prevents lower back rounding.',
 4, '10-12 reps', 45, 90, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

-- ==================== FULL BODY ====================
(28, 'Burpees', 'burpees', 'Full Body', 'Intermediate', 'No Equipment',
 'Full Body Muscular & Aerobic System', 'Chest, Quads, Core, Triceps, Calves',
 'Dynamic full-body calisthenics powerhouse testing cardiovascular endurance, power output, and speed.',
 'Step 1\nStand tall with feet shoulder-width apart.\n\nStep 2\nDrop hips back, plant hands on floor, and kick feet back into a plank.\n\nStep 3\nDrop chest and thighs completely to touch the floor.\n\nStep 4\nPush up forcefully through hands while jumping feet back under hips.\n\nStep 5\nExplode vertically into the air, reaching hands overhead with a clap.\n\nStep 6\nLand softly on balls of feet and immediately flow into the next repetition.',
 'Bending from lower back rather than hips, skipping full floor chest contact, stiff-legged landing.',
 'Pace your breathing rhythmically: exhale on the jump up, inhale on the floor drop.',
 'Step back instead of jumping back if high-impact landing causes knee or ankle strain.',
 4, '12-15 reps', 45, 60, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4', 'assets/images/content/cardio.webp', 'ACTIVE'),

(29, 'Kettlebell Swing', 'kettlebell-swing', 'Full Body', 'Intermediate', 'Kettlebell',
 'Glutes, Hamstrings, Posterior Chain', 'Latissimus, Core, Grip, Cardiovascular System',
 'Ballistic hip-hinge power movement that builds explosive glutes, core rigidity, and metabolic stamina.',
 'Step 1\nStand with feet shoulder-width apart, kettlebell 1 foot in front of you on floor.\n\nStep 2\nHinge at hips with flat spine and grab bell handle with both hands.\n\nStep 3\nHike bell back between legs like a football pass to load hamstrings and glutes.\n\nStep 4\nDrive hips forward explosively and squeeze glutes to float bell to chest height.\n\nStep 5\nLet bell freefall back between legs, catching momentum with hips in a hinge.\n\nStep 6\nRepeat in a fluid rhythmic cadence.',
 'Squatting the bell down instead of hinging hips, pulling bell with arms/shoulders, arching back at top.',
 'Your arms are just ropes: 100% of the upward propulsion comes from explosive hip snap.',
 'Keep your neck neutral; do not look up at the ceiling during the bottom hinge.',
 4, '15-20 reps', 45, 60, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

(30, 'Thrusters', 'thrusters', 'Full Body', 'Advanced', 'Dumbbells / Barbell',
 'Quadriceps, Deltoids, Glutes', 'Triceps, Core, Upper Back, Cardiovascular System',
 'Compound hybrid fusing a deep front squat with an overhead press for unmatched metabolic conditioning.',
 'Step 1\nStand with feet shoulder-width apart, holding dumbbells at shoulders with palms facing.\n\nStep 2\nDescend into a full front squat, breaking at hips and knees with proud chest.\n\nStep 3\nReach parallel or below with knees tracking wide over toes.\n\nStep 4\nExplode upward through mid-foot with maximum leg drive.\n\nStep 5\nTransfer leg momentum directly into pressing the dumbbells overhead in one fluid motion.\n\nStep 6\nLower dumbbells back to shoulders as you smoothly descend into the next squat.',
 'Pausing between squat and press (breaks kinetic chain), pressing before legs finish driving.',
 'Use leg drive momentum to launch the dumbbells overhead; don\'t treat it as two separate lifts.',
 'Ensure core is locked tight at overhead peak to prevent lower back hyper-extension.',
 3, '10-12 reps', 45, 90, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/WeAreGoingOnBullrun.mp4', 'assets/images/content/strength-training.webp', 'ACTIVE'),

-- ==================== MOBILITY ====================
(31, 'Hip Flexor Stretch', 'hip-flexor-stretch', 'Mobility', 'Beginner', 'Mat',
 'Iliopsoas, Rectus Femoris (Hip Flexors)', 'Glutes, Quadriceps, Core',
 'Essential restorative stretch that unlocks chronically tight hip flexors caused by prolonged sitting.',
 'Step 1\nKneel on a comfortable mat and step right foot forward into a half-kneeling 90/90 stance.\n\nStep 2\nEnsure your torso is completely upright with hands resting on front knee.\n\nStep 3\nTuck your pelvis into a posterior tilt by squeezing your left glute.\n\nStep 4\nShift bodyweight gently forward 2-3 inches until you feel a deep stretch in front of left hip.\n\nStep 5\nReach left arm straight overhead and lean gently to the right to deepen stretch.\n\nStep 6\nHold for 30-45 seconds while breathing deeply into belly, then switch sides.',
 'Arching lower back to fake hip depth, shifting forward too far without posterior pelvic tilt.',
 'Tuck your tailbone under like a scared dog first; this immediately targets the psoas.',
 'Place a soft foam pad under the rear knee if kneeling on hard ground.',
 3, '30-45 seconds/side', 40, 30, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4', 'assets/images/content/mobility.webp', 'ACTIVE'),

(32, 'Shoulder Mobility Flow', 'shoulder-mobility', 'Mobility', 'Beginner', 'No Equipment / Band',
 'Rotator Cuff, Deltoids, Pectoralis Minor', 'Thoracic Spine, Trapezius',
 'Multi-planar mobility flow designed to restore overhead shoulder range and release thoracic tightness.',
 'Step 1\nStand tall with feet hip-width and arms relaxed at your sides.\n\nStep 2\nSlowly raise arms straight overhead, keeping ribs down and core engaged.\n\nStep 3\nReach as tall as possible without shrugging shoulders up to ears.\n\nStep 4\nRotate palms outward and sweep arms down and back in a large circular arc.\n\nStep 5\nInterlace fingers behind back and gently open chest for 3 deep breaths.\n\nStep 6\nRepeat smoothly for 8-10 slow, fluid arm circles in each direction.',
 'Arching spine to force arms overhead, rushing through sticky points in range of motion.',
 'Breathe into tight areas of resistance and move with smooth, controlled circular paths.',
 'Do not force movements through sharp pinching pain; work within pain-free boundaries.',
 3, '8-10 circles', 40, 30, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4', 'assets/images/content/mobility.webp', 'ACTIVE'),

(33, 'Hamstring Stretch', 'hamstring-stretch', 'Mobility', 'Beginner', 'Mat / Bench',
 'Biceps Femoris, Semitendinosus (Hamstrings)', 'Calves, Glutes, Lower Back',
 'Safe functional stretch that relieves hamstring tightness and decompresses the posterior chain.',
 'Step 1\nSit on floor with right leg extended straight and left foot tucked against inner right thigh.\n\nStep 2\nSit tall and pull toes of right foot back toward your shin (dorsiflexion).\n\nStep 3\nHinge forward from your hips with a flat spine, leading with your chest.\n\nStep 4\nReach hands toward right shin, ankle, or toes until a pleasant stretch is felt.\n\nStep 5\nHold the position without bouncing, taking slow diaphragmatic breaths.\n\nStep 6\nHold for 30-45 seconds, release smoothly, and switch to left leg.',
 'Rounding upper back and hunching shoulders to touch toes, locking knee aggressively, bouncing.',
 'Lead with your chest, not your forehead: hinging from hips produces 3x better hamstring release.',
 'Keep a micro-bend in the knee if you feel tension in the back of the knee joint.',
 3, '30-45 seconds/side', 40, 30, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4', 'assets/images/content/mobility.webp', 'ACTIVE'),

(34, 'Cat-Cow Flow', 'cat-cow', 'Mobility', 'Beginner', 'Mat',
 'Erector Spinae, Core, Thoracic Spine', 'Neck, Pelvic Floor, Shoulders',
 'Synchronized spinal articulation flow that mobilizes every vertebra and eases lower back stiffness.',
 'Step 1\nBegin on all fours on a mat with wrists directly under shoulders and knees under hips.\n\nStep 2\nInhale slowly into Cow Pose: drop belly toward floor, lift chest and tailbone, gaze forward.\n\nStep 3\nFeel a gentle stretch across your abdomen and thoracic spine.\n\nStep 4\nExhale smoothly into Cat Pose: tuck tailbone under, round spine toward ceiling, tuck chin to chest.\n\nStep 5\nPush floor away through palms to spread shoulder blades apart.\n\nStep 6\nFlow smoothly between Cat and Cow in rhythm with your natural respiration for 10 cycles.',
 'Moving too quickly, forcing extreme neck extension, collapsing shoulders into wrists.',
 'Articulate one vertebra at a time: imagine a slow wave moving from your tailbone to the crown of your head.',
 'Move gently within your comfortable pain-free range of motion.',
 3, '10 cycles', 45, 30, 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyBlazes.mp4', 'assets/images/content/mobility.webp', 'ACTIVE');
